from typing import Literal, TypedDict

SourceName = Literal["eu_ai_act", "gdpr", "nist_ai_rmf"]
ValidationStatus = Literal["passed", "failed", "not_checked"]


# TypedDict defines the structure of the data dictionary
# that will move through the LangGraph workflow.
#
# In LangGraph, this shared dictionary is called the "state".
# Each node receives this state, reads values from it,
# and returns updated values.
class RetrievedDocument(TypedDict):
    """
    Clean structure for retrieved document chunks.

    We do not store raw LangChain Document objects in the graph state.
    Instead, we convert them into simple dictionaries.

    Why?
    - Easier to print
    - Easier to debug
    - Easier to show in Streamlit later
    - Easier to serialize if needed
    """

    source_name: str
    file_name: str
    page: int | str
    content: str


class PolicyAgentState(TypedDict):
    """
    Shared state for the LangGraph workflow.
    """

    # The original question asked by the user
    question: str

    # The type/category of the question.
    # Literal restricts allowed values to only these options.
    # This helps avoid spelling mistakes like "definiton".
    question_type: Literal["definition", "compliance", "risk", "unknown"]

    selected_sources: list[SourceName]

    # Retrieved evidence chunks from the vector store.
    retrieved_documents: list[RetrievedDocument]

    # LLM-generated answer.
    answer: str
    revised_answer: str

    validation_status: ValidationStatus
    validation_feedback: str
    llm_error: str

    # The final text response generated by the graph
    response: str
